# Generated by Django 6.0.2 on 2026-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('lanches', 'Lanches / Pratos'), ('bebidas', 'Bebidas'), ('sobremesas', 'Sobremesas'), ('porcoes', 'Porções / Extras')], default='lanches', max_length=20, verbose_name='Categoria'),
        ),
    ]
