# Generated by Django 6.0.2 on 2026-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_configuracao_horario_funcionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='horario_info',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='domingo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='horario_abertura',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='horario_fechamento',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='quarta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='quinta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='sabado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='segunda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='sexta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='terca',
            field=models.BooleanField(default=True),
        ),
    ]
