# Generated by Django 6.0.2 on 2026-02-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoria_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='meta_diaria',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='horario_abertura',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='horario_fechamento',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_empresa',
            field=models.CharField(default='Minha Empresa', max_length=100),
        ),
    ]
