# Generated by Django 6.0.2 on 2026-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pedido_endereco_pedido_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.AddField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número/Lote'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua/Alameda'),
        ),
    ]
