# Generated by Django 6.0.2 on 2026-02-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_estoque_produto_estoque_atual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Insumo')),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd em Estoque')),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilo'), ('g', 'Grama'), ('un', 'Unidade'), ('l', 'Litro')], default='un', max_length=5, verbose_name='Unidade')),
                ('preco_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Compra')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque_atual',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_compra',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ultima_saida',
        ),
    ]
