# Generated by Django 6.0.2 on 2026-02-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pedido_entregador_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_identificador',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
