# Generated by Django 6.0.2 on 2026-02-18 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_insumo_loja_pedido_loja_produto_loja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='loja',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nome', 'loja')},
        ),
    ]
