# Generated by Django 6.0.2 on 2026-02-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_categoria_loja_configuracao_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_entrega',
            field=models.CharField(blank=True, choices=[('AGUARDANDO', 'Aguardando Coleta'), ('EM_ROTA', 'Em Rota de Entrega'), ('ENTREGUE', 'Entregue ao Cliente'), ('CANCELADO', 'Entrega Cancelada'), ('PENDENTE', 'Pendente'), ('PREPARANDO', 'Preparando'), ('PRONTO', 'Pronto para Entrega'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20, null=True),
        ),
    ]
