# Generated by Django 6.0.2 on 2026-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_pedido_status_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PREPARANDO', 'Preparando'), ('PRONTO', 'Pronto para Entrega'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_entrega',
            field=models.CharField(blank=True, choices=[('AGUARDANDO', 'Aguardando Entregador'), ('EM_ROTA', 'Em Rota'), ('ENTREGUE', 'Entregue')], default='AGUARDANDO', max_length=20, null=True),
        ),
    ]
