# Generated by Django 6.0.2 on 2026-02-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pedido_status_pedido_alter_pedido_status_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='loja_aberta',
            field=models.BooleanField(default=True, verbose_name='Loja Aberta Manualmente'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='meta_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='visualizacoes_cardapio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
