# Generated by Django 6.0.2 on 2026-02-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_perfil_cnh_perfil_cpf_perfil_placa_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entregue',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora que foi entregue'),
        ),
    ]
