# Generated by Django 6.0.2 on 2026-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Minha Empresa', max_length=100)),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('horario_funcionamento', models.CharField(default='Aberto agora', max_length=100)),
            ],
        ),
    ]
