# Generated by Django 6.0.2 on 2026-02-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='horario_funcionamento',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='horario_info',
            field=models.CharField(default='Aberto • Fecha às 23:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='nome_empresa',
            field=models.CharField(default='SID Burguer & Co.', max_length=100),
        ),
    ]
