# Generated by Django 6.0.2 on 2026-02-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracao_meta_diaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='visualizacoes_cardapio',
            field=models.IntegerField(default=0),
        ),
    ]
