# Generated by Django 6.0.2 on 2026-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracao_visualizacoes_cardapio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='preco_momento',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sessao_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
