# Generated by Django 6.0.2 on 2026-02-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_preco_momento_itempedido_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
