# Generated by Django 6.0.2 on 2026-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pedido_endereco_pedido_bairro_pedido_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
    ]
