# Generated by Django 6.0.2 on 2026-02-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_produto_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='estoque_atual',
        ),
        migrations.AddField(
            model_name='produto',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Compra'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ultima_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Saída'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda'),
        ),
    ]
