# Generated by Django 6.0.2 on 2026-02-18 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_produto_preco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entregador_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitar_entrega',
            field=models.BooleanField(default=False, verbose_name='Solicitar Entregadora?'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_entrega',
            field=models.CharField(blank=True, choices=[('AGUARDANDO', 'Aguardando Coleta'), ('EM_ROTA', 'Em Rota de Entrega'), ('ENTREGUE', 'Entregue ao Cliente'), ('CANCELADO', 'Entrega Cancelada')], default='AGUARDANDO', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Admin Geral'), ('LOJISTA', 'Lojista'), ('ENTREGADORA', 'Empresa de Entrega')], default='LOJISTA', max_length=20)),
                ('nome_empresa', models.CharField(blank=True, help_text='Nome da Loja ou Transportadora', max_length=100, null=True)),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Conta Ativa?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
