# Generated by Django 6.0.2 on 2026-02-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_perfil_codigo_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome_empresa',
            field=models.CharField(blank=True, help_text='Nome da Loja ou Transportadora', max_length=100, null=True, unique=True),
        ),
    ]
