# Generated by Django 6.0.2 on 2026-02-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_configuracao_loja_aberta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='domingo_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='domingo_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='quarta_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='quarta_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='quinta_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='quinta_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='sabado_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='sabado_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='segunda_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='segunda_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='sexta_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='sexta_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='terca_abertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='terca_fechamento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
