# Generated by Django 6.0.2 on 2026-02-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_configuracao_horario_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_saida_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora que saiu para entrega'),
        ),
    ]
