# Generated by Django 6.0.2 on 2026-02-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_pedido_data_saida_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='veiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Veículo'),
        ),
    ]
